all: testimony testimonyd

clean: testimony_clean testimonyd_clean

.PHONY: testimony testimonyd

testimony:
	$(MAKE) -C testimony

testimony_clean:
	$(MAKE) -C testimony clean

testimonyd:
	$(MAKE) -C testimonyd

testimonyd_clean:
	$(MAKE) -C testimonyd clean
